### ISSUE TITLE
Autonomous robot navigation 

### ISSUE THREAD

**Issue by MappsGames13** [yoraish/lidar_bot#1]
Question 1. is it possible to make the robot autonomous in such a way that it moves in an entire room without hector slam?

Question 2 : After saving the map generated by hector slam, how to make the robot autonomous ?

**Comment by yoraish** [comment]
Hello! 

A slight delay in responding, but here we are :).

1. From my understanding you are seeking to navigate in an unknown environment without creating a map? If that's the case, I think you might be able to perform simply obstacle avoidance and get it to work. I would process the lidar data and determine if facing an obstacle. If so, change orientation and progress. If I understood you incorrectly, please let me know!
2.  Expect some updates soon! I have been working on it and I think that I got it to work just now. I'll update here and at yoraish.com.
